export interface Vehicle {
  id: string;
  name: string;
  brand: string;
  category: "suv" | "sedan" | "truck" | "hybrid" | "sports";
  price: number;
  year: number;
  mileage: number;
  engine: string;
  horsepower: number;
  transmission: string;
  acceleration: string;
  fuelType: string;
  image: string;
  badge?: string;
  tagline: string;
}

export const vehicles: Vehicle[] = [
  {
    id: "nissan-gtr-r35",
    name: "Nissan GT-R R35 Premium Edition",
    brand: "Nissan",
    category: "sports",
    price: 85000000,
    year: 2021,
    mileage: 4800,
    engine: "3.8L Twin-Turbo VR38DETT V6",
    horsepower: 565,
    transmission: "6-Speed Dual-Clutch with Paddle Shifters",
    acceleration: "2.8 sec",
    fuelType: "Gasoline",
    image: "/inventory/nissan-gtr-r35.jpg",
    badge: "Grand Opening · Flagship",
    tagline: "Showroom flagship supercar finished in Super Silver Metallic with titanium quad exhausts and ATTESA E-TS AWD.",
  },
  {
    id: "lexus-rx500h",
    name: "Lexus RX 500h F SPORT Performance",
    brand: "Lexus",
    category: "hybrid",
    price: 68000000,
    year: 2024,
    mileage: 2400,
    engine: "2.4L Turbo Hybrid DIRECT4 AWD",
    horsepower: 366,
    transmission: "6-Speed Automatic DIRECT4",
    acceleration: "5.9 sec",
    fuelType: "Turbo Hybrid",
    image: "/inventory/lexus-rx500h-fsport.jpg",
    badge: "F SPORT Performance",
    tagline: "Obsidian Black with custom quad aero diffuser, Dynamic Rear Steering (DRS), and F SPORT bespoke cabin.",
  },
  {
    id: "mini-jcw",
    name: "MINI Countryman John Cooper Works",
    brand: "MINI",
    category: "sports",
    price: 46500000,
    year: 2024,
    mileage: 1200,
    engine: "2.0L TwinPower Turbo JCW ALL4",
    horsepower: 312,
    transmission: "7-Speed Steptronic Sport DCT",
    acceleration: "5.4 sec",
    fuelType: "Gasoline",
    image: "/inventory/mini-countryman-jcw.jpg",
    badge: "Demo Plate K26-0745",
    tagline: "Exclusive Midnight Black with Chili Red contrast roof, aerodynamic JCW styling pack, and ALL4 AWD.",
  },
  {
    id: "honda-vezel-rs",
    name: "Honda Vezel e:HEV RS Sport",
    brand: "Honda",
    category: "hybrid",
    price: 19500000,
    year: 2024,
    mileage: 3200,
    engine: "1.5L e:HEV Dual-Motor Hybrid",
    horsepower: 131,
    transmission: "e-CVT Intelligent Hybrid",
    acceleration: "8.5 sec",
    fuelType: "Hybrid (26.0 km/L)",
    image: "/inventory/honda-vezel-rs.jpg",
    badge: "Unregistered · RS Sport",
    tagline: "Platinum White Pearl with RS body styling, gloss black aero grille, and Honda SENSING driver-assist suite.",
  },
  {
    id: "jaguar-xe",
    name: "Jaguar XE R-Sport Luxury Sedan",
    brand: "Jaguar",
    category: "sedan",
    price: 28500000,
    year: 2018,
    mileage: 38500,
    engine: "2.0L Turbocharged Ingenium 4-Cyl",
    horsepower: 247,
    transmission: "8-Speed Quickshift Automatic",
    acceleration: "6.5 sec",
    fuelType: "Gasoline",
    image: "/inventory/jaguar-xe-rsport.jpg",
    badge: "WP CBA Registered",
    tagline: "Finished in vivid Firenze Red with premium leather interior, Meridian sound system, and dynamic handling.",
  },
  {
    id: "toyota-raize-modellista",
    name: "Toyota Raize Z Modellista Edition",
    brand: "Toyota",
    category: "suv",
    price: 17200000,
    year: 2023,
    mileage: 6800,
    engine: "1.0L Turbo 1KR-VET Intercooled",
    horsepower: 98,
    transmission: "D-CVT Automatic",
    acceleration: "9.4 sec",
    fuelType: "Gasoline Turbo",
    image: "/inventory/toyota-raize-modellista.jpg",
    badge: "Modellista Aero Pack",
    tagline: "Equipped with authentic Modellista Aero kit, blue LED signature illumination spoiler, and two-tone roof.",
  },
  {
    id: "toyota-raize-z",
    name: "Toyota Raize Z Package Two-Tone",
    brand: "Toyota",
    category: "hybrid",
    price: 16800000,
    year: 2023,
    mileage: 9200,
    engine: "1.2L e-SMART Hybrid System",
    horsepower: 106,
    transmission: "Direct-Drive Automatic",
    acceleration: "8.9 sec",
    fuelType: "Hybrid",
    image: "/inventory/toyota-raize-z-front.jpg",
    badge: "Top-Spec Z Package",
    tagline: "Pearl White with Black roof, 17-inch turbine alloy wheels, LED sequential indicators, and Smart Assist radar.",
  },
  {
    id: "toyota-pixis",
    name: "Toyota Pixis Epoch Eco-Idle",
    brand: "Toyota",
    category: "hybrid",
    price: 7850000,
    year: 2023,
    mileage: 8400,
    engine: "660cc KF-VE DOHC Topaz Neo",
    horsepower: 52,
    transmission: "Super CVT-i Automatic",
    acceleration: "12.5 sec",
    fuelType: "Eco-Idle Petrol",
    image: "/inventory/toyota-pixis-epoch.jpg",
    badge: "Unregistered · Grade 4.5",
    tagline: "Ultra fuel-efficient Japanese city hatchback delivering 35.2 km/L with Toyota Safety Sense emergency braking.",
  },
  {
    id: "suzuki-every",
    name: "Suzuki Every PC High-Roof",
    brand: "Suzuki",
    category: "suv",
    price: 8200000,
    year: 2023,
    mileage: 12500,
    engine: "660cc R06A VVT High-Efficiency",
    horsepower: 49,
    transmission: "5-Speed AGS Automatic",
    acceleration: "13.8 sec",
    fuelType: "Gasoline",
    image: "/inventory/suzuki-every-van.jpg",
    badge: "Unregistered · High Roof",
    tagline: "Rare Cool Khaki metallic finish with high-roof dual sliding doors, spacious cargo utility, and safety radar.",
  },
  {
    id: "toyota-land-cruiser",
    name: "Toyota Land Cruiser 250 Prado",
    brand: "Toyota",
    category: "suv",
    price: 58000000,
    year: 2024,
    mileage: 2100,
    engine: "i-FORCE MAX 2.4L Turbo Hybrid",
    horsepower: 326,
    transmission: "8-Speed Automatic 4WD",
    acceleration: "6.8 sec",
    fuelType: "Hybrid",
    image: "/inventory/toyota-land-cruiser-250.png",
    badge: "Just Arrived",
    tagline: "All-new 250 Series in Silver with heritage TOYOTA grille, Multi-Terrain Select, and flagship luxury.",
  },
  {
    id: "mercedes-c300",
    name: "Mercedes-Benz C 300 AMG Line",
    brand: "Mercedes-Benz",
    category: "sedan",
    price: 38500000,
    year: 2024,
    mileage: 3800,
    engine: "2.0L Turbo with EQ Boost Mild Hybrid",
    horsepower: 255,
    transmission: "9G-TRONIC Automatic",
    acceleration: "5.9 sec",
    fuelType: "Mild Hybrid",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80",
    badge: "Low Mileage",
    tagline: "S-Class inspired interior elegance with digital light technology and advanced driver-assist safety.",
  },
  {
    id: "bmw-330i",
    name: "BMW 330i M Sport",
    brand: "BMW",
    category: "sedan",
    price: 36000000,
    year: 2024,
    mileage: 6300,
    engine: "2.0L TwinPower Turbo 4-Cylinder",
    horsepower: 255,
    transmission: "8-Speed Sport Automatic",
    acceleration: "5.4 sec",
    fuelType: "Gasoline",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    badge: "Executive",
    tagline: "The benchmark sports sedan with razor-sharp handling and BMW curved display cockpit.",
  },
];