export interface Vehicle {
  id: string;
  name: string;
  brand: string;
  category: "suv" | "sedan" | "truck" | "hybrid" | "sports";
  price: number;
  year: number;
  mileage: number;
  engine: string;
  horsepower: number;
  transmission: string;
  acceleration: string;
  fuelType: string;
  image: string;
  badge?: string;
  tagline: string;
}

export const vehicles: Vehicle[] = [
  {
    id: "1",
    name: "Toyota RAV4 Prime XSE",
    brand: "Toyota",
    category: "hybrid",
    price: 43500,
    year: 2024,
    mileage: 3200,
    engine: "2.5L 4-Cylinder Plug-In Hybrid",
    horsepower: 302,
    transmission: "CVT All-Wheel Drive",
    acceleration: "5.7 sec",
    fuelType: "Plug-in Hybrid",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    badge: "Popular Hybrid",
    tagline: "High efficiency paired with exceptional versatility and all-wheel drive confidence.",
  },
  {
    id: "2",
    name: "Honda Civic Sport Touring",
    brand: "Honda",
    category: "sedan",
    price: 29800,
    year: 2024,
    mileage: 1800,
    engine: "1.5L Turbocharged 4-Cylinder",
    horsepower: 180,
    transmission: "CVT Automatic",
    acceleration: "7.2 sec",
    fuelType: "Gasoline",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
    badge: "Great Value",
    tagline: "Sporty styling, outstanding fuel economy, and class-leading reliability.",
  },
  {
    id: "3",
    name: "Hyundai Ioniq 5 Limited",
    brand: "Hyundai",
    category: "hybrid",
    price: 47900,
    year: 2024,
    mileage: 4100,
    engine: "Dual Motor Electric AWD",
    horsepower: 320,
    transmission: "Single-Speed Automatic",
    acceleration: "4.5 sec",
    fuelType: "Electric",
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    badge: "All-Electric",
    tagline: "Futuristic design with ultra-fast 800V charging and lounge-style cabin.",
  },
  {
    id: "4",
    name: "Toyota Land Cruiser 250 First Edition",
    brand: "Toyota",
    category: "suv",
    price: 74900,
    year: 2024,
    mileage: 800,
    engine: "i-FORCE MAX 2.4L Turbo Hybrid",
    horsepower: 326,
    transmission: "8-Speed Automatic 4WD",
    acceleration: "6.8 sec",
    fuelType: "Hybrid",
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80",
    badge: "Just Arrived",
    tagline: "Legendary off-road capability reimagined with modern hybrid power.",
  },
  {
    id: "5",
    name: "Honda CR-V Hybrid Sport-L",
    brand: "Honda",
    category: "suv",
    price: 36500,
    year: 2024,
    mileage: 5200,
    engine: "2.0L 4-Cylinder Two-Motor Hybrid",
    horsepower: 204,
    transmission: "Electronic CVT",
    acceleration: "7.6 sec",
    fuelType: "Hybrid",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    badge: "Family Favorite",
    tagline: "Spacious, comfortable, and remarkably efficient for everyday family driving.",
  },
  {
    id: "6",
    name: "Hyundai Tucson N Line AWD",
    brand: "Hyundai",
    category: "suv",
    price: 34200,
    year: 2024,
    mileage: 2600,
    engine: "2.5L Smartstream 4-Cylinder",
    horsepower: 187,
    transmission: "8-Speed Automatic",
    acceleration: "8.2 sec",
    fuelType: "Gasoline",
    image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
    badge: "Certified",
    tagline: "Bold angular styling with premium interior tech and comprehensive warranty.",
  },
  {
    id: "7",
    name: "Ford F-150 Lariat SuperCrew",
    brand: "Ford",
    category: "truck",
    price: 58900,
    year: 2023,
    mileage: 11400,
    engine: "3.5L PowerBoost Full Hybrid V6",
    horsepower: 430,
    transmission: "10-Speed Automatic 4x4",
    acceleration: "5.3 sec",
    fuelType: "Hybrid",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    badge: "Towing Package",
    tagline: "America's best-selling truck with integrated Pro Power Onboard generator.",
  },
  {
    id: "8",
    name: "BMW 330i xDrive M Sport",
    brand: "BMW",
    category: "sedan",
    price: 46800,
    year: 2024,
    mileage: 3900,
    engine: "2.0L TwinPower Turbo 4-Cylinder",
    horsepower: 255,
    transmission: "8-Speed Sport Automatic",
    acceleration: "5.4 sec",
    fuelType: "Gasoline",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    badge: "Executive",
    tagline: "The benchmark sports sedan with razor-sharp handling and intuitive tech.",
  },
  {
    id: "9",
    name: "Mercedes-Benz C 300 4MATIC",
    brand: "Mercedes-Benz",
    category: "sedan",
    price: 48500,
    year: 2024,
    mileage: 2100,
    engine: "2.0L Turbo with Mild Hybrid Assist",
    horsepower: 255,
    transmission: "9G-TRONIC Automatic",
    acceleration: "5.9 sec",
    fuelType: "Mild Hybrid",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80",
    badge: "Low Mileage",
    tagline: "S-Class inspired interior elegance with advanced driver-assist safety.",
  },
];